const defaultState={name:"",position:"Winger",xp:0,level:1,streak:1,bestRT:null,bestCombo:1,dailyDone:false,packOpened:false,lastXp:0};
let state=load(), selectedPosition=state.position||"Winger";
let trainTime=60, trainScore=0, trainCombo=1, trainTimer=null, expected=["red"], recognition=null;
let stream=null, camLoop=null, prevFrame=null, waiting=false, cueStart=0, camScore=0;
const cues=[{cue:"🔴",a:["red"]},{cue:"🔵",a:["blue"]},{cue:"←",a:["left"]},{cue:"→",a:["right"]},{cue:"8 - 3",a:["5","five"]},{cue:"CHECK",a:["check"]}];
const camCues=["←","→","⬆","⬇","TURN","DRIVE","CHECK"];
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem("pitchiqSprint3")||"{}")}}catch(e){return {...defaultState}}}
function save(){localStorage.setItem("pitchiqSprint3",JSON.stringify(state))}
document.addEventListener("DOMContentLoaded",()=>{sparkles();bindPositions();refresh();});
function sparkles(){const s=document.getElementById("sparkles");if(!s)return;for(let i=0;i<70;i++){let e=document.createElement("span");e.className="spark";e.style.left=Math.random()*100+"%";e.style.top=Math.random()*100+"%";e.style.animationDelay=Math.random()*4+"s";s.appendChild(e)}}
function bindPositions(){document.querySelectorAll(".positions button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".positions button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedPosition=b.dataset.pos})}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");refresh()}
function enterApp(){state.name?showScreen("dashboard"):showScreen("onboard")}
function completeOnboarding(){state.name=document.getElementById("nameInput").value.trim()||"Player";state.position=selectedPosition;save();showScreen("dashboard");toast("Welcome to PitchIQ Academy")}
function resetProfile(){if(confirm("Reset profile?")){localStorage.removeItem("pitchiqSprint3");location.reload()}}
function xpNeed(){return state.level*600}
function rank(){if(state.level>=10)return"Academy";if(state.level>=6)return"Division 1";if(state.level>=3)return"Local Club";return"Grassroots"}
function addXP(n){state.xp+=n;state.lastXp+=n;while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;toast("LEVEL UP 🏆");beep(950,.08);setTimeout(()=>beep(1300,.08),90)}save();refresh()}
function refresh(){document.querySelectorAll(".playerName").forEach(e=>e.textContent=state.name||"Player");by("positionBadge").textContent=state.position||"Winger";by("streak").textContent=state.streak;by("level").textContent=state.level;by("rank").textContent=rank();by("xp").textContent=state.xp;by("xpNeed").textContent=xpNeed();by("leaderXp").textContent=(state.xp+(state.level-1)*600)+" XP";by("nextRank").textContent=state.level<3?"Local Club":state.level<6?"Division 1":"Academy";by("xpBar").style.width=Math.min(100,state.xp/xpNeed()*100)+"%";by("packText").textContent=state.dailyDone?(state.packOpened?"Opened: Academy Boots unlocked.":"Unlocked: tap to open."):"Locked: complete today’s mission.";by("questSession").classList.toggle("done",state.dailyDone);drawChart();by("bestRT").textContent=state.bestRT?state.bestRT+" ms":"—";}
function by(id){return document.getElementById(id)}
function toast(t){let e=by("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1200)}
function beep(f,d){try{let c=new(AudioContext||webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.05;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){}}
function speak(t){try{let u=new SpeechSynthesisUtterance(t);u.rate=1.06;speechSynthesis.speak(u)}catch(e){}}
function drawChart(){let c=by("chart");if(!c)return;let ctx=c.getContext("2d"),data=[80,140,220,180,310,state.xp||90,state.lastXp||120];ctx.clearRect(0,0,c.width,c.height);data.forEach((v,i)=>{let h=Math.min(200,v/420*200),x=42+i*82,y=225-h,g=ctx.createLinearGradient(0,y,0,225);g.addColorStop(0,"#d8ff2f");g.addColorStop(1,"#24ff9a");ctx.fillStyle=g;round(ctx,x,y,46,h,14);ctx.fill();ctx.fillStyle="rgba(246,255,248,.66)";ctx.font="900 15px system-ui";ctx.fillText(["M","T","W","T","F","S","S"][i],x+15,260)})}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function startTraining(){trainTime=60;trainScore=0;trainCombo=1;state.lastXp=0;updateTrain();nextCue();clearInterval(trainTimer);speak("Three. Two. One. Go.");trainTimer=setInterval(()=>{trainTime--;updateTrain();if(trainTime<=0)endTraining()},1000)}
function nextCue(){let c=cues[Math.floor(Math.random()*cues.length)];expected=c.a;by("cue").textContent=c.cue;by("instruction").textContent="Say or tap: "+expected[0].toUpperCase();beep(880,.06)}
function answer(a){expected.includes(a)?correct():wrong()}
function correct(){let gain=20*trainCombo;trainScore+=gain;addXP(gain);trainCombo=Math.min(9,trainCombo+1);state.bestCombo=Math.max(state.bestCombo,trainCombo);save();updateTrain();toast("+"+gain+" XP 🔥");beep(980,.07);setTimeout(()=>beep(1320,.08),90);nextCue()}
function wrong(){trainScore=Math.max(0,trainScore-10);trainCombo=1;updateTrain();toast("Reset. Next cue.");beep(180,.18);nextCue()}
function updateTrain(){by("time").textContent=trainTime;by("score").textContent=trainScore;by("combo").textContent=trainCombo}
function endTraining(){clearInterval(trainTimer);state.dailyDone=true;save();showScreen("reward");toast("Session complete 🏆")}
function startVoice(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast("Voice not supported");return}recognition=new SR();recognition.lang="en-AU";recognition.continuous=true;recognition.interimResults=false;recognition.onresult=e=>{let heard=e.results[e.results.length-1][0].transcript.toLowerCase().trim();expected.some(a=>heard.includes(a))?correct():toast("Heard: "+heard)};recognition.onend=()=>{try{recognition.start()}catch(e){}};try{recognition.start();toast("Voice enabled 🎤")}catch(e){}}
async function testVideo(){let el=by("videoStatus");try{let t=await navigator.mediaDevices.getUserMedia({video:true,audio:false});t.getTracks().forEach(x=>x.stop());el.textContent="Video access works.";toast("Camera test passed 📷")}catch(e){el.textContent="Camera blocked or unavailable.";toast("Camera test failed")}}
async function startCamera(facingMode="environment"){try{if(stream)stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode},audio:false});let v=by("video");v.srcObject=stream;await v.play();toast((facingMode==="user"?"Front":"Rear")+" camera on");loopMotion()}catch(e){toast("Camera permission needed")}}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(camLoop)cancelAnimationFrame(camLoop)}
function loopMotion(){let v=by("video"),c=by("motion"),ctx=c.getContext("2d",{willReadFrequently:true});let w=160,h=90;c.width=w;c.height=h;function loop(){if(v.readyState>=2){ctx.drawImage(v,0,0,w,h);let img=ctx.getImageData(0,0,w,h),m=motion(img.data);if(waiting&&m>Number(by("sensitivity").value)&&performance.now()-cueStart>120)detected(performance.now()-cueStart);prevFrame=new Uint8ClampedArray(img.data)}camLoop=requestAnimationFrame(loop)}loop()}
function motion(data){if(!prevFrame)return 0;let d=0,n=0;for(let i=0;i<data.length;i+=16){d+=(Math.abs(data[i]-prevFrame[i])+Math.abs(data[i+1]-prevFrame[i+1])+Math.abs(data[i+2]-prevFrame[i+2]))/3;n++}return d/n}
function cameraRound(){if(!stream){toast("Enable camera first");return}let cue=camCues[Math.floor(Math.random()*camCues.length)],el=by("cameraCue");el.className="go";el.textContent=cue;waiting=true;cueStart=performance.now();beep(950,.08);speak(String(cue).replace("←","left").replace("→","right").replace("⬆","forward").replace("⬇","back"));setTimeout(()=>{if(waiting){waiting=false;el.className="";el.textContent="MISS";toast("Too slow 😮")}},2500)}
function detected(ms){waiting=false;let rt=Math.round(ms),gain=rt<350?90:rt<550?70:rt<800?45:25;camScore+=gain;by("camScore").textContent=camScore;by("lastRT").textContent=rt+" ms";by("cameraCue").className="detected";by("cameraCue").textContent=rt+" ms";if(!state.bestRT||rt<state.bestRT){state.bestRT=rt;toast("New best: "+rt+" ms 🏆")}else toast("Reaction: "+rt+" ms");state.dailyDone=true;addXP(gain);save();beep(1150,.07)}
function openPack(){if(!state.dailyDone){toast("Complete a session first");return}by("rewardPack").classList.add("open");setTimeout(()=>{by("rewardTitle").textContent="Academy Boots Unlocked!";by("rewardText").textContent="+100 XP bonus added.";if(!state.packOpened){state.packOpened=true;addXP(100)}save()},650)}
function showSummary(){by("sumXp").textContent=state.lastXp;by("sumRt").textContent=state.bestRT?state.bestRT+" ms":"—";by("sumCombo").textContent="x"+state.bestCombo}
setInterval(()=>{if(document.getElementById("summary").classList.contains("active"))showSummary()},500)
