const titles={home:"Good afternoon, Hugo",train:"Training Session",career:"Your Career",player:"Build Your Player",rewards:"Daily Rewards",club:"Club Battle",analytics:"Progress Analytics",watch:"Apple Watch Concept"};
document.querySelectorAll(".nav,.profile").forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.screen===id));document.getElementById("title").textContent=titles[id]||"PitchIQ";if(id==="analytics")drawChart();}
let score=0,combo=1,time=45,timer=null;const cues=[["🔴","Say RED"],["🔵","Say BLUE"],["🟢","Say GREEN"],["CHECK","Check shoulder"],["DRIVE","Attack space"],["8 - 3","Say FIVE"],["←","Cut LEFT"],["→","Cut RIGHT"]];
function startDemo(){score=0;combo=1;time=45;update();nextCue();clearInterval(timer);timer=setInterval(()=>{time--;update();if(time<=0){clearInterval(timer);toast("Session complete 🏆");speak("Session complete");}},1000);speak("Three. Two. One. Go.");}
function nextCue(){const c=cues[Math.floor(Math.random()*cues.length)];document.getElementById("cue").textContent=c[0];document.getElementById("instruction").textContent=c[1];beep(900,.06);}
function correct(){score+=20*combo;combo=Math.min(combo+1,9);update();toast("+XP 🔥");beep(1000,.07);setTimeout(()=>beep(1350,.08),90);nextCue();}
function wrong(){score=Math.max(0,score-10);combo=1;update();toast("-10 XP 😮");beep(180,.18);nextCue();}
function update(){document.getElementById("score").textContent=score;document.getElementById("combo").textContent="x"+combo;document.getElementById("time").textContent="0:"+String(time).padStart(2,"0");}
function toast(t){let e=document.getElementById("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1100);}
function beep(f,d){try{let c=new (AudioContext||webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.05;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d);}catch(e){}}
function speak(t){try{speechSynthesis.speak(new SpeechSynthesisUtterance(t));}catch(e){}}
function openPack(){document.getElementById("packTitle").textContent="New Stadium Unlocked!";toast("Reward unlocked 🏟️");}
function career(){const ranks=["Grassroots","Local","Div 3","Div 2","Div 1","Academy","NPL","A-League","Ballon d'Or"];["miniCareer","careerMap"].forEach(id=>{let el=document.getElementById(id);if(!el)return;el.innerHTML="";ranks.forEach((r,i)=>{let n=document.createElement("div");n.className="node "+(i<5?"done":i==5?"current":"");n.innerHTML=`<div class="badge">${i<5?"✅":i==5?"⭐":"🔒"}</div><small>${r}</small>`;el.appendChild(n);});});}
function heat(){let h=document.getElementById("heatmap");if(!h)return;h.innerHTML="";for(let i=0;i<156;i++){let d=document.createElement("div"),v=Math.random();d.className="hcell "+(v>.8?"h3":v>.55?"h2":v>.35?"h1":"");h.appendChild(d);}}
function drawChart(){let c=document.getElementById("chart");if(!c)return;let x=c.getContext("2d"),data=[180,310,420,300,520,260,360];x.clearRect(0,0,c.width,c.height);data.forEach((v,i)=>{let h=v/600*260,xx=40+i*115,y=310-h,g=x.createLinearGradient(0,y,0,310);g.addColorStop(0,"#b8ff22");g.addColorStop(1,"#2dff95");x.fillStyle=g;x.fillRect(xx,y,54,h);x.fillStyle="#9fb4a8";x.font="900 16px system-ui";x.fillText(["M","T","W","T","F","S","S"][i],xx+18,340);});}
career();heat();drawChart();