let playerName=localStorage.getItem("pitchiqName")||"";
let score=0,combo=1,time=45,timer=null;
let cameraScore=0, stream=null, camLoop=null, prevFrame=null, cueStart=0, waitingForMove=false, bestRT=Number(localStorage.getItem("pitchiqBestRT")||0);
const cues=[["🔴","Say RED"],["🔵","Say BLUE"],["🟢","Say GREEN"],["CHECK","Check shoulder"],["DRIVE","Attack space"],["8 - 3","Say FIVE"],["←","Cut LEFT"],["→","Cut RIGHT"]];
const cameraCues=["←","→","⬆","⬇","TURN","DRIVE","CHECK"];
function init(){if(!playerName)document.getElementById("nameModal").classList.add("active");else{document.getElementById("nameModal").classList.remove("active");applyName();}updateBestRT();}
function savePlayerName(){playerName=document.getElementById("nameInput").value.trim()||"Player";localStorage.setItem("pitchiqName",playerName);document.getElementById("nameModal").classList.remove("active");applyName();}
function resetName(){localStorage.removeItem("pitchiqName");playerName="";document.getElementById("nameInput").value="";document.getElementById("nameModal").classList.add("active");}
function applyName(){document.querySelectorAll(".playerName").forEach(e=>e.textContent=playerName);}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");}
function startDemo(){score=0;combo=1;time=45;update();nextCue();clearInterval(timer);timer=setInterval(()=>{time--;update();if(time<=0){clearInterval(timer);toast("Session complete 🏆");speak("Session complete");}},1000);speak("Three. Two. One. Go.");}
function nextCue(){const c=cues[Math.floor(Math.random()*cues.length)];document.getElementById("cue").textContent=c[0];document.getElementById("instruction").textContent=c[1];beep(900,.06);}
function correct(){score+=20*combo;combo=Math.min(combo+1,9);update();toast("+XP 🔥");beep(1000,.07);setTimeout(()=>beep(1350,.08),90);nextCue();}
function wrong(){score=Math.max(0,score-10);combo=1;update();toast("-10 XP 😮");beep(180,.18);nextCue();}
function update(){document.getElementById("score").textContent=score;document.getElementById("combo").textContent="x"+combo;document.getElementById("time").textContent="0:"+String(time).padStart(2,"0");}
async function testVideoAccess(){const el=document.getElementById("videoTest");if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){el.textContent="Video status: camera API not supported.";return;}try{const t=await navigator.mediaDevices.getUserMedia({video:true,audio:false});t.getTracks().forEach(x=>x.stop());el.textContent="Video status: camera access works.";toast("Camera test passed 📷");}catch(e){el.textContent="Video status: permission denied or unavailable.";toast("Camera test failed");}}
async function startCamera(facingMode="environment"){try{if(stream)stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode},audio:false});const v=document.getElementById("video");v.srcObject=stream;await v.play();document.getElementById("cameraStatus").textContent=(facingMode==="user"?"Front":"Rear")+" camera on";toast("Camera enabled 📷");startMotionLoop();}catch(e){document.getElementById("cameraStatus").textContent="No access";toast("Camera permission needed");}}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}if(camLoop)cancelAnimationFrame(camLoop);document.getElementById("cameraStatus").textContent="Stopped";}
function startMotionLoop(){const video=document.getElementById("video"),canvas=document.getElementById("motionCanvas"),ctx=canvas.getContext("2d",{willReadFrequently:true});const w=160,h=90;canvas.width=w;canvas.height=h;function loop(){if(video.readyState>=2){ctx.drawImage(video,0,0,w,h);const img=ctx.getImageData(0,0,w,h),motion=calculateMotion(img.data);if(waitingForMove){const threshold=Number(document.getElementById("sensitivity").value);if(motion>threshold&&performance.now()-cueStart>120)movementDetected(performance.now()-cueStart);}prevFrame=new Uint8ClampedArray(img.data);}camLoop=requestAnimationFrame(loop);}loop();}
function calculateMotion(data){if(!prevFrame)return 0;let diff=0,count=0;for(let i=0;i<data.length;i+=16){diff+=(Math.abs(data[i]-prevFrame[i])+Math.abs(data[i+1]-prevFrame[i+1])+Math.abs(data[i+2]-prevFrame[i+2]))/3;count++;}return diff/count;}
function calibrateMotion(){toast("Stillness calibrated");document.getElementById("cameraStatus").textContent="Calibrated";}
function startCameraRound(){if(!stream){toast("Enable camera first");return;}const cue=cameraCues[Math.floor(Math.random()*cameraCues.length)],el=document.getElementById("cameraCue");el.className="camera-cue go";el.textContent=cue;waitingForMove=true;cueStart=performance.now();document.getElementById("cameraStatus").textContent="Move now";beep(950,.08);speak(String(cue).replace("←","left").replace("→","right").replace("⬆","forward").replace("⬇","back"));setTimeout(()=>{if(waitingForMove){waitingForMove=false;el.className="camera-cue";el.textContent="MISS";document.getElementById("cameraStatus").textContent="Too slow";toast("Too slow 😮");beep(180,.18);if(document.getElementById("autoRounds").checked)setTimeout(startCameraRound,1100);}},2500);}
function movementDetected(ms){waitingForMove=false;const rt=Math.round(ms);cameraScore+=scoreForRT(rt);const el=document.getElementById("cameraCue");el.className="camera-cue detected";el.textContent=rt+" ms";document.getElementById("lastRT").textContent=rt+" ms";document.getElementById("cameraScore").textContent=cameraScore;document.getElementById("cameraStatus").textContent="Detected";if(!bestRT||rt<bestRT){bestRT=rt;localStorage.setItem("pitchiqBestRT",String(bestRT));updateBestRT();toast("New best: "+rt+" ms 🏆");}else toast("Reaction: "+rt+" ms");beep(1150,.07);setTimeout(()=>beep(1450,.08),80);if(document.getElementById("autoRounds").checked)setTimeout(startCameraRound,1200);}
function scoreForRT(rt){if(rt<350)return 80;if(rt<550)return 60;if(rt<800)return 40;if(rt<1200)return 20;return 5;}
function updateBestRT(){const txt=bestRT?bestRT+" ms":"—";let el=document.getElementById("bestRT");if(el)el.textContent=txt;}
function toast(t){let e=document.getElementById("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1200);}
function beep(f,d){try{let c=new(AudioContext||webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.05;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d);}catch(e){}}
function speak(t){try{let u=new SpeechSynthesisUtterance(t);u.rate=1.08;speechSynthesis.speak(u);}catch(e){}}
init();
