const ROUTE="lab-calmsense";
const RETURN_ROUTE="world-lab";
const STYLE_ID="pitchiq-calmsense-css";
const SAMPLE_LIMIT=600;
let session=null;

function route(){return location.hash.replace(/^#/,"").toLowerCase()}
function app(){return document.getElementById("app")}
function ensureStyle(){if(document.getElementById(STYLE_ID))return;const link=document.createElement("link");link.id=STYLE_ID;link.rel="stylesheet";link.href="css/lab-calmsense.css?v=sprint-l1-0-20260721";document.head.appendChild(link)}
function stop(){if(!session)return;window.removeEventListener("devicemotion",session.onMotion);clearInterval(session.clock);session=null}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function shell(content){return `<section class="calmsense-screen"><header class="calmsense-topbar"><button type="button" data-calmsense-back aria-label="Back to Lab">‹</button><div><span>PitchIQ Lab</span><strong>CalmSense</strong></div><em class="calmsense-badge">EXPERIMENTAL</em></header>${content}</section>`}
function intro(){return shell(`<section class="calmsense-card calmsense-intro"><span class="calmsense-badge">PHONE MOTION SENSOR</span><h1>Reset your breathing.</h1><p>Place your phone flat on the centre of your chest while lying safely on your back. CalmSense estimates breathing rhythm from gentle chest movement.</p><div class="calmsense-steps"><div class="calmsense-step"><i>1</i><span><strong>Lie on your back</strong><small>Use a safe, comfortable surface.</small></span></div><div class="calmsense-step"><i>2</i><span><strong>Phone on chest</strong><small>Keep one hand nearby so it cannot fall.</small></span></div><div class="calmsense-step"><i>3</i><span><strong>Breathe naturally</strong><small>Stay still while the signal calibrates.</small></span></div></div><button class="calmsense-primary" data-calmsense-start>Start 30-second test</button><p class="calmsense-copy"><small>Training feedback only — not a medical device. Stop if uncomfortable. Do not use while standing, walking or driving.</small></p></section>`)}
function sessionMarkup(){return shell(`<section class="calmsense-card calmsense-session"><span class="calmsense-badge">CALIBRATING</span><h1 id="calmTitle">Breathe naturally</h1><p class="calmsense-copy" id="calmPrompt">Keep still while CalmSense finds your breathing rhythm.</p><div class="calmsense-ring" id="calmRing"><div class="calmsense-ring-value"><b id="calmTime">30</b><span>seconds remaining</span></div></div><canvas class="calmsense-wave" id="calmWave" width="600" height="160" aria-label="Live breathing waveform"></canvas><div class="calmsense-metrics"><div class="calmsense-metric"><small>Breaths / min</small><b id="calmBpm">—</b></div><div class="calmsense-metric"><small>Signal quality</small><b id="calmQualityLabel">Finding</b></div></div><div class="calmsense-quality"><span id="calmQuality"></span></div><p class="calmsense-status" id="calmStatus">Waiting for motion sensor…</p><button class="calmsense-secondary" data-calmsense-end>End test</button><pre class="calmsense-dev" id="calmDev">samples: 0\npeaks: 0\nmotion artifacts: 0</pre></section>`)}
function resultsMarkup(result){return shell(`<section class="calmsense-card calmsense-results"><span class="calmsense-badge">SESSION COMPLETE</span><h1>Your CalmSense result</h1><div class="calmsense-score"><div><b>${result.score}</b><small>Calm score</small></div></div><div class="calmsense-metrics"><div class="calmsense-metric"><small>Average rate</small><b>${result.bpm?result.bpm.toFixed(1):"—"}</b></div><div class="calmsense-metric"><small>Consistency</small><b>${result.consistency}%</b></div><div class="calmsense-metric"><small>Signal quality</small><b>${result.quality}%</b></div><div class="calmsense-metric"><small>Movement flags</small><b>${result.artifacts}</b></div></div><p class="calmsense-copy">${escapeHtml(result.message)}</p><button class="calmsense-primary" data-calmsense-retry>Try again</button><button class="calmsense-secondary" data-calmsense-back>Back to Lab</button></section>`)}
function variance(values){if(values.length<2)return 0;const mean=values.reduce((a,b)=>a+b,0)/values.length;return values.reduce((s,v)=>s+(v-mean)**2,0)/values.length}
function dominantAxis(samples){const axes=["x","y","z"];return axes.sort((a,b)=>variance(samples.map(s=>s[b]))-variance(samples.map(s=>s[a])))[0]}
function smooth(values,alpha=.12){let out=[],last=values[0]||0;for(const value of values){last=last+alpha*(value-last);out.push(last)}return out}
function detrend(values,windowSize=45){const out=[];let sum=0;for(let i=0;i<values.length;i++){sum+=values[i];if(i>=windowSize)sum-=values[i-windowSize];const n=Math.min(i+1,windowSize);out.push(values[i]-sum/n)}return out}
function detectPeaks(values,times){if(values.length<45)return[];const recent=values.slice(-450);const recentTimes=times.slice(-450);const sd=Math.sqrt(variance(recent));const threshold=Math.max(.006,sd*.35);const peaks=[];let last=-Infinity;for(let i=2;i<recent.length-2;i++){if(recent[i]>threshold&&recent[i]>=recent[i-1]&&recent[i]>recent[i+1]&&recent[i]>=recent[i-2]&&recent[i]>recent[i+2]){const t=recentTimes[i];if(t-last>1800){peaks.push(t);last=t}}}return peaks}
function analyse(s){const axis=s.axis||dominantAxis(s.samples.slice(0,Math.min(120,s.samples.length)));s.axis=axis;const raw=s.samples.map(v=>v[axis]);const filtered=smooth(detrend(raw));const peaks=detectPeaks(filtered,s.samples.map(v=>v.t));const intervals=peaks.slice(1).map((p,i)=>p-peaks[i]).filter(v=>v>1800&&v<15000);const avg=intervals.length?intervals.reduce((a,b)=>a+b,0)/intervals.length:0;const bpm=avg?60000/avg:0;const intervalCv=intervals.length>1?Math.sqrt(variance(intervals))/(avg||1):1;const amplitude=Math.sqrt(variance(filtered.slice(-250)));const quality=Math.round(Math.max(0,Math.min(100,(amplitude/.018)*55+(intervals.length>=2?35:intervals.length*12)-s.artifacts*3)));const consistency=Math.round(Math.max(0,Math.min(100,100-intervalCv*100)));return{axis,filtered,peaks,intervals,bpm,quality,consistency,amplitude}}
function draw(values){const canvas=document.getElementById("calmWave");if(!canvas)return;const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="rgba(72,227,181,.18)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,canvas.height/2);ctx.lineTo(canvas.width,canvas.height/2);ctx.stroke();if(values.length<2)return;const data=values.slice(-240);const max=Math.max(.02,...data.map(v=>Math.abs(v)));ctx.strokeStyle="#48e3b5";ctx.lineWidth=4;ctx.beginPath();data.forEach((v,i)=>{const x=i/(data.length-1)*canvas.width;const y=canvas.height/2-(v/max)*(canvas.height*.38);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function update(){if(!session)return;const analysis=analyse(session);session.analysis=analysis;draw(analysis.filtered);const elapsed=(Date.now()-session.started)/1000;const remain=Math.max(0,30-Math.floor(elapsed));document.getElementById("calmTime").textContent=remain;document.getElementById("calmBpm").textContent=analysis.bpm?analysis.bpm.toFixed(1):"—";document.getElementById("calmQualityLabel").textContent=analysis.quality>=70?"Good":analysis.quality>=40?"Fair":"Finding";document.getElementById("calmQuality").style.setProperty("--quality",`${analysis.quality}%`);document.getElementById("calmStatus").textContent=session.artifacts>3?"Too much movement — keep the phone still.":analysis.bpm?"Breathing rhythm detected.":"Breathe naturally and remain still.";document.getElementById("calmDev").textContent=`axis: ${analysis.axis}\nsamples: ${session.samples.length}\npeaks: ${analysis.peaks.length}\namplitude: ${analysis.amplitude.toFixed(4)}\nmotion artifacts: ${session.artifacts}`;const phase=analysis.filtered.at(-1)||0;document.getElementById("calmRing").style.setProperty("--calm-scale",String(Math.max(.86,Math.min(1.15,1+phase*5))));if(remain<=0)finish()}
function onMotion(event){if(!session)return;const a=event.accelerationIncludingGravity||event.acceleration;if(!a)return;const now=Date.now();const sample={t:now,x:Number(a.x)||0,y:Number(a.y)||0,z:Number(a.z)||0};const previous=session.samples.at(-1);if(previous){const delta=Math.hypot(sample.x-previous.x,sample.y-previous.y,sample.z-previous.z);if(delta>.45)session.artifacts++}session.samples.push(sample);if(session.samples.length>SAMPLE_LIMIT)session.samples.shift()}
async function permission(){if(typeof DeviceMotionEvent==="undefined")return false;if(typeof DeviceMotionEvent.requestPermission==="function"){try{return(await DeviceMotionEvent.requestPermission())==="granted"}catch{return false}}return true}
async function start(){const granted=await permission();if(!granted){document.getElementById("calmStatus")?.remove();app().innerHTML=shell(`<section class="calmsense-card"><h1>Motion access is required</h1><p class="calmsense-copy">Allow Motion & Orientation Access in Safari settings, then reopen CalmSense.</p><button class="calmsense-primary" data-calmsense-retry>Try again</button></section>`);return}app().innerHTML=sessionMarkup();session={started:Date.now(),samples:[],artifacts:0,axis:null,analysis:null,onMotion,clock:null};window.addEventListener("devicemotion",onMotion,{passive:true});session.clock=setInterval(update,250);update()}
function finish(){if(!session)return;const analysis=session.analysis||analyse(session);const result={bpm:analysis.bpm,quality:analysis.quality,consistency:analysis.consistency,artifacts:session.artifacts,score:Math.round(Math.max(0,Math.min(100,analysis.quality*.45+analysis.consistency*.35+(analysis.bpm>=5&&analysis.bpm<=10?20:10)))),message:analysis.quality<40?"The signal was weak. Try a flatter phone position and less body movement.":analysis.bpm?"CalmSense detected a repeating breathing rhythm. Treat this as training feedback, not a clinical measurement.":"Not enough complete breaths were detected. Try again while staying still."};stop();localStorage.setItem("pitchiqCalmSenseLast",JSON.stringify({...result,completedAt:Date.now()}));app().innerHTML=resultsMarkup(result)}
function render(){if(route()!==ROUTE){stop();return false}ensureStyle();document.body.classList.remove("pitchiq-splash-active");document.getElementById("nav")?.classList.remove("visible");app().innerHTML=intro();return true}
document.addEventListener("click",event=>{const startButton=event.target.closest?.("[data-calmsense-start]");if(startButton){event.preventDefault();start();return}const end=event.target.closest?.("[data-calmsense-end]");if(end){event.preventDefault();finish();return}const retry=event.target.closest?.("[data-calmsense-retry]");if(retry){event.preventDefault();app().innerHTML=intro();return}const back=event.target.closest?.("[data-calmsense-back]");if(back){event.preventDefault();stop();location.hash=RETURN_ROUTE}},true);
window.addEventListener("hashchange",render);window.addEventListener("pageshow",render);render();
