const ROUTE="lab-calmsense",RETURN_ROUTE="world-lab",STYLE_ID="pitchiq-calmsense-css",SAMPLE_LIMIT=900,HISTORY_KEY="pitchiqCalmSenseValidationHistory";
let session=null,lastResult=null;
const route=()=>location.hash.replace(/^#/,"").toLowerCase(),app=()=>document.getElementById("app");
function ensureStyle(){let link=document.getElementById(STYLE_ID);if(link){link.href="css/lab-calmsense.css?v=sprint-l1-1-20260721";return}link=document.createElement("link");link.id=STYLE_ID;link.rel="stylesheet";link.href="css/lab-calmsense.css?v=sprint-l1-1-20260721";document.head.appendChild(link)}
function stop(){if(!session)return;window.removeEventListener("devicemotion",session.onMotion);clearInterval(session.clock);session=null}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function shell(content){return `<section class="calmsense-screen"><header class="calmsense-topbar"><button type="button" data-calmsense-back aria-label="Back to Lab">‹</button><div><span>PitchIQ Lab</span><strong>CalmSense</strong></div><em class="calmsense-badge">VALIDATION</em></header>${content}</section>`}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]").slice(0,10)}catch{return[]}}
function saveHistory(item){const next=[item,...history()].slice(0,10);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));return next}
function mean(values){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0}
function variance(values){if(values.length<2)return 0;const m=mean(values);return mean(values.map(v=>(v-m)**2))}
function dashboardMarkup(){const rows=history(),compared=rows.filter(r=>Number.isFinite(r.manualBpm)),success=rows.filter(r=>r.detected).length,mae=mean(compared.map(r=>r.error)),quality=mean(rows.map(r=>r.quality)),confidence=mean(rows.map(r=>r.confidence));return `<section class="calmsense-dashboard"><header><strong>Last ${rows.length} validation tests</strong><small>Stored on this device only</small></header><div class="calmsense-metrics"><div class="calmsense-metric"><small>Mean error</small><b>${compared.length?mae.toFixed(1):"—"}</b></div><div class="calmsense-metric"><small>Detection rate</small><b>${rows.length?Math.round(success/rows.length*100):0}%</b></div><div class="calmsense-metric"><small>Avg signal</small><b>${Math.round(quality)}%</b></div><div class="calmsense-metric"><small>Avg confidence</small><b>${Math.round(confidence)}%</b></div></div>${rows.length?`<div class="calmsense-history">${rows.map(r=>`<div><span>${new Date(r.completedAt).toLocaleDateString()}</span><b>${r.bpm?r.bpm.toFixed(1):"—"} BPM</b><em>${esc(r.classification)}</em></div>`).join("")}</div>`:'<p class="calmsense-copy">Complete a test to begin the validation record.</p>'}</section>`}
function intro(){return shell(`<section class="calmsense-card calmsense-intro"><span class="calmsense-badge">PHONE MOTION SENSOR</span><h1>Validate the signal.</h1><p>CalmSense now begins with a 10-second signal check, then records breathing rate, movement and confidence for comparison with a manual count.</p><div class="calmsense-steps"><div class="calmsense-step"><i>1</i><span><strong>Lie safely on your back</strong><small>Place the phone flat at the centre of your chest.</small></span></div><div class="calmsense-step"><i>2</i><span><strong>Stay still for calibration</strong><small>The first 10 seconds assess signal quality.</small></span></div><div class="calmsense-step"><i>3</i><span><strong>Count your breaths</strong><small>Enter your manual count after the test.</small></span></div></div><button class="calmsense-primary" data-calmsense-start>Start validation test</button><p class="calmsense-copy"><small>Training feedback only — not a medical device.</small></p></section>${dashboardMarkup()}`)}
function sessionMarkup(){return shell(`<section class="calmsense-card calmsense-session"><span class="calmsense-badge" id="calmPhase">SIGNAL CHECK</span><h1 id="calmTitle">Keep still</h1><p class="calmsense-copy" id="calmPrompt">CalmSense is checking phone position and breathing movement.</p><div class="calmsense-ring" id="calmRing"><div class="calmsense-ring-value"><b id="calmTime">40</b><span>seconds remaining</span></div></div><canvas class="calmsense-wave" id="calmWave" width="600" height="160"></canvas><div class="calmsense-metrics"><div class="calmsense-metric"><small>Estimated BPM</small><b id="calmBpm">—</b></div><div class="calmsense-metric"><small>Detected breaths</small><b id="calmBreaths">0</b></div><div class="calmsense-metric"><small>Signal</small><b id="calmQualityLabel">Finding</b></div><div class="calmsense-metric"><small>Confidence</small><b id="calmConfidence">0%</b></div></div><div class="calmsense-quality"><span id="calmQuality"></span></div><p class="calmsense-status" id="calmStatus">Waiting for motion sensor…</p><button class="calmsense-secondary" data-calmsense-end>End test</button><pre class="calmsense-dev" id="calmDev"></pre></section>`)}
function resultsMarkup(r){return shell(`<section class="calmsense-card calmsense-results"><span class="calmsense-badge">SESSION COMPLETE</span><h1>${esc(r.classification)} signal</h1><div class="calmsense-score"><div><b>${r.confidence}</b><small>Confidence</small></div></div><div class="calmsense-metrics"><div class="calmsense-metric"><small>Estimated rate</small><b>${r.bpm?r.bpm.toFixed(1):"—"}</b></div><div class="calmsense-metric"><small>Breaths detected</small><b>${r.breaths}</b></div><div class="calmsense-metric"><small>Signal quality</small><b>${r.quality}%</b></div><div class="calmsense-metric"><small>Movement flags</small><b>${r.artifacts}</b></div></div><label class="calmsense-manual"><span>Manual breaths per minute</span><input inputmode="decimal" type="number" min="1" max="60" step="0.1" id="calmManualBpm" placeholder="Enter your count"></label><p class="calmsense-comparison" id="calmComparison">Enter your manual rate to calculate error.</p><button class="calmsense-primary" data-calmsense-save>Save comparison</button><button class="calmsense-secondary" data-calmsense-retry>Try again</button><button class="calmsense-secondary" data-calmsense-back>Back to Lab</button></section>`)}
function dominantAxis(samples){return ["x","y","z"].sort((a,b)=>variance(samples.map(s=>s[b]))-variance(samples.map(s=>s[a])))[0]}
function smooth(values,alpha=.12){let out=[],last=values[0]||0;for(const value of values){last+=alpha*(value-last);out.push(last)}return out}
function detrend(values,w=45){const out=[];let sum=0;for(let i=0;i<values.length;i++){sum+=values[i];if(i>=w)sum-=values[i-w];out.push(values[i]-sum/Math.min(i+1,w))}return out}
function detectPeaks(values,times){if(values.length<45)return[];const recent=values.slice(-600),recentTimes=times.slice(-600),sd=Math.sqrt(variance(recent)),threshold=Math.max(.006,sd*.35),peaks=[];let last=-Infinity;for(let i=2;i<recent.length-2;i++){if(recent[i]>threshold&&recent[i]>=recent[i-1]&&recent[i]>recent[i+1]&&recent[i]>=recent[i-2]&&recent[i]>recent[i+2]&&recentTimes[i]-last>1800){peaks.push(recentTimes[i]);last=recentTimes[i]}}return peaks}
function analyse(s){const axis=s.axis||dominantAxis(s.samples.slice(0,Math.min(160,s.samples.length)));s.axis=axis;const raw=s.samples.map(v=>v[axis]),filtered=smooth(detrend(raw)),peaks=detectPeaks(filtered,s.samples.map(v=>v.t)),intervals=peaks.slice(1).map((p,i)=>p-peaks[i]).filter(v=>v>1800&&v<15000),avg=mean(intervals),bpm=avg?60000/avg:0,cv=intervals.length>1?Math.sqrt(variance(intervals))/(avg||1):1,amplitude=Math.sqrt(variance(filtered.slice(-300))),sampleRate=s.samples.length>1?1000*(s.samples.length-1)/(s.samples.at(-1).t-s.samples[0].t):0,quality=Math.round(Math.max(0,Math.min(100,(amplitude/.018)*50+(intervals.length>=2?38:intervals.length*12)-s.artifacts*2.5))),consistency=Math.round(Math.max(0,Math.min(100,100-cv*100))),confidence=Math.round(Math.max(0,Math.min(100,quality*.55+consistency*.3+(intervals.length>=3?15:intervals.length*4))));return{axis,filtered,peaks,intervals,bpm,quality,consistency,confidence,amplitude,sampleRate}}
function draw(values){const canvas=document.getElementById("calmWave");if(!canvas)return;const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="rgba(72,227,181,.18)";ctx.beginPath();ctx.moveTo(0,80);ctx.lineTo(600,80);ctx.stroke();if(values.length<2)return;const data=values.slice(-300),max=Math.max(.02,...data.map(v=>Math.abs(v)));ctx.strokeStyle="#48e3b5";ctx.lineWidth=4;ctx.beginPath();data.forEach((v,i)=>{const x=i/(data.length-1)*600,y=80-v/max*61;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function update(){if(!session)return;const a=analyse(session);session.analysis=a;draw(a.filtered);const elapsed=(Date.now()-session.started)/1000,calibrating=elapsed<10,remain=Math.max(0,40-Math.floor(elapsed));document.getElementById("calmTime").textContent=remain;document.getElementById("calmPhase").textContent=calibrating?"SIGNAL CHECK":"LIVE TEST";document.getElementById("calmTitle").textContent=calibrating?"Keep still":"Breathe naturally";document.getElementById("calmBpm").textContent=a.bpm?a.bpm.toFixed(1):"—";document.getElementById("calmBreaths").textContent=a.peaks.length;document.getElementById("calmConfidence").textContent=`${a.confidence}%`;const state=session.artifacts>4?"Movement":a.quality>=70?"Good":a.quality>=40?"Weak":"Finding";document.getElementById("calmQualityLabel").textContent=state;document.getElementById("calmQuality").style.setProperty("--quality",`${a.quality}%`);document.getElementById("calmStatus").textContent=state==="Movement"?"Excessive movement — keep the phone still.":calibrating?"Checking signal quality…":a.bpm?"Breathing rhythm detected.":"Breathing not detected yet.";document.getElementById("calmDev").textContent=`axis: ${a.axis}\nsample rate: ${a.sampleRate.toFixed(1)} Hz\nsamples: ${session.samples.length}\npeaks: ${a.peaks.length}\nsignal: ${a.quality}%\nconfidence: ${a.confidence}%\nmotion artifacts: ${session.artifacts}`;document.getElementById("calmRing").style.setProperty("--calm-scale",String(Math.max(.86,Math.min(1.15,1+(a.filtered.at(-1)||0)*5))));if(remain<=0)finish()}
function onMotion(event){if(!session)return;const a=event.accelerationIncludingGravity||event.acceleration;if(!a)return;const sample={t:Date.now(),x:Number(a.x)||0,y:Number(a.y)||0,z:Number(a.z)||0},prev=session.samples.at(-1);if(prev&&Math.hypot(sample.x-prev.x,sample.y-prev.y,sample.z-prev.z)>.45)session.artifacts++;session.samples.push(sample);if(session.samples.length>SAMPLE_LIMIT)session.samples.shift()}
async function permission(){if(typeof DeviceMotionEvent==="undefined")return false;if(typeof DeviceMotionEvent.requestPermission==="function"){try{return await DeviceMotionEvent.requestPermission()==="granted"}catch{return false}}return true}
async function start(){if(!await permission()){app().innerHTML=shell(`<section class="calmsense-card"><h1>Motion access is required</h1><p class="calmsense-copy">Allow Motion & Orientation Access in Safari settings, then reopen CalmSense.</p><button class="calmsense-primary" data-calmsense-retry>Try again</button></section>`);return}app().innerHTML=sessionMarkup();session={started:Date.now(),samples:[],artifacts:0,axis:null,analysis:null,onMotion,clock:null};window.addEventListener("devicemotion",onMotion,{passive:true});session.clock=setInterval(update,250);update()}
function classify(a,artifacts){if(a.confidence>=80&&a.quality>=70&&artifacts<=2)return"Excellent";if(a.confidence>=65&&a.quality>=55)return"Good";if(a.confidence>=40)return"Fair";return"Poor"}
function finish(){if(!session)return;const a=session.analysis||analyse(session);lastResult={bpm:a.bpm,breaths:a.peaks.length,quality:a.quality,consistency:a.consistency,confidence:a.confidence,artifacts:session.artifacts,axis:a.axis,sampleRate:a.sampleRate,detected:Boolean(a.bpm),classification:classify(a,session.artifacts),completedAt:Date.now()};stop();app().innerHTML=resultsMarkup(lastResult)}
function saveComparison(){if(!lastResult)return;const input=document.getElementById("calmManualBpm"),manual=Number(input?.value);if(!Number.isFinite(manual)||manual<=0){document.getElementById("calmComparison").textContent="Enter a valid manual breaths-per-minute value.";return}lastResult.manualBpm=manual;lastResult.error=Math.abs((lastResult.bpm||0)-manual);saveHistory(lastResult);document.getElementById("calmComparison").textContent=`Absolute error: ${lastResult.error.toFixed(1)} breaths/min. Saved locally.`;document.querySelector("[data-calmsense-save]").disabled=true}
function render(){if(route()!==ROUTE){stop();return false}ensureStyle();document.body.classList.remove("pitchiq-splash-active");document.getElementById("nav")?.classList.remove("visible");app().innerHTML=intro();return true}
document.addEventListener("click",event=>{if(event.target.closest?.("[data-calmsense-start]")){event.preventDefault();start();return}if(event.target.closest?.("[data-calmsense-end]")){event.preventDefault();finish();return}if(event.target.closest?.("[data-calmsense-save]")){event.preventDefault();saveComparison();return}if(event.target.closest?.("[data-calmsense-retry]")){event.preventDefault();app().innerHTML=intro();return}if(event.target.closest?.("[data-calmsense-back]")){event.preventDefault();stop();location.hash=RETURN_ROUTE}},true);
window.addEventListener("hashchange",render);window.addEventListener("pageshow",render);render();