import { stat } from "../components/ui.js";
import { rankForLevel, xpNeed } from "../game/progression.js";
import { recommendedDrills } from "../data/drills.js";
import { REWARDS, CAREER_RANKS, ACHIEVEMENTS } from "../data/rewards.js";

export const routeNames = ["home","training","results","player"];

const POSITION_LABELS = {
  ST: "Striker", LW: "Left Wing", RW: "Right Wing", CAM: "Attacking Midfielder", CM: "Central Midfielder", CDM: "Defensive Midfielder", LB: "Left Back", RB: "Right Back", CB: "Centre Back", GK: "Goalkeeper", Winger: "Winger", Striker: "Striker", FB: "Full Back"
};
const PLAYER_POSITIONS = Object.entries(POSITION_LABELS).filter(([code])=>code.length<=3);
const PLAYER_STYLES = ["Creator","Finisher","Playmaker","Engine","Controller","Defender","Sweeper Keeper"];

function positionLabel(position="Winger"){ return POSITION_LABELS[position] || position || "Winger"; }
function playerOverall(state){ return Math.min(99,60+state.game.level+(state.analytics.bestReaction?4:0)); }
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);}

export function AcademyHeroPanel(){return `<section class="AcademyHeroPanel" aria-label="Youth footballer scanning the field"><svg class="academy-hero-svg" viewBox="0 0 320 236" role="img" aria-labelledby="academyHeroTitle academyHeroDesc" preserveAspectRatio="xMidYMid meet"><title id="academyHeroTitle">PitchIQ Academy hero</title><desc id="academyHeroDesc">A youth footballer scans over the shoulder while an incoming ball and left-right scan arcs show football intelligence training.</desc><rect width="320" height="236" rx="28" fill="#020807"/></svg></section>`}
function renderOnboardPositionSelector(){const positions=[["ST","st","47.83%","26.43%","Select striker"],["LW","lw","26.87%","26.41%","Select left wing"],["RW","rw","69.35%","26.40%","Select right wing"],["CAM","cam","47.98%","38.15%","Select attacking midfielder"],["CM","cm","31.62%","47.51%","Select central midfielder"],["CDM","cdm","64.50%","47.44%","Select defensive midfielder"],["LB","lb","17.25%","61.56%","Select left back"],["CB","cb1","38.06%","61.55%","Select centre back"],["CB","cb2","58.70%","61.54%","Select centre back"],["RB","rb","80.39%","61.54%","Select right back"],["GK","gk","47.70%","73.30%","Select goalkeeper"]];return `<div class="academy-pitch position-selector position-game-layer" role="group" aria-label="Choose Position"><img class="position-pitch-layer position-pitch-inactive" src="assets/onboarding/position-pitch-inactive.png?v=single-pitch-20260621" alt="" aria-hidden="true"><div class="position-marker-box">${positions.map(([p,slot,x,y,label])=>`<button type="button" data-pos="${p}" data-slot="${slot}" class="pitch-node position-marker" style="left:${x};top:${y}" aria-label="${label}"><span aria-hidden="true"></span><b aria-hidden="true">${p}</b></button>`).join("")}</div></div>`}
export function renderSplash(){return `<section class="screen center active splash-v1 splash-academy-v2 splash-cover-v3" id="splash"><div class="splash-content splash-academy-content"><h1 class="splash-title-v1 splash-academy-title"><span>TRAIN THE <em>BRAIN</em></span><span>BEHIND THE <em>GAME</em></span></h1></div></section>`}
export function renderOnboard(){return `<section class="screen center active onboard-v1" id="onboard"><div class="onboard-content onboarding-wizard"><section class="onboard-step" data-onboard-step="1"><span class="position-title">Step 1 of 3</span><p class="onboard-subtitle">MAKE IT YOURS</p><h1 class="onboard-heading">Who's training?</h1><input id="nameInput" class="onboard-name-input" aria-label="Player name" placeholder="Your name" maxlength="18" autocomplete="name"><button class="primary mega" data-action="onboard-next-name" disabled>CONTINUE →</button></section><section class="onboard-step" data-onboard-step="2" hidden><span class="position-title">Step 2 of 3</span><h1 class="onboard-position-heading">POSITION</h1>${renderOnboardPositionSelector()}<div id="positionConfirm" class="position-confirm"><span>Selected:</span><b>—</b></div><button class="primary mega" data-action="onboard-next-position" disabled>CONTINUE →</button></section><section class="onboard-step" data-onboard-step="3" hidden><span class="position-title">Step 3 of 3</span><h1>Enter<br>Academy</h1><div class="onboard-confirm-card"><small>Player</small><b id="confirmName">—</b><small>Position</small><strong id="confirmPosition">—</strong></div><button class="primary mega" data-action="save-profile">ENTER ACADEMY →</button></section></div></section>`}
export function renderMission(state){return `<section class="screen center active" id="mission"><div class="mission-card"><span class="kicker">🔥 Day ${state.game.streak} mission</span><h1>Beat yesterday.</h1><button class="primary mega" data-route="home">Continue</button></div></section>`}
function homeMetrics(state){const need=xpNeed(state.game.level),rank=rankForLevel(state.game.level),pct=Math.min(100,Math.round(state.game.xp/need*100)),overall=playerOverall(state);return{need,rank,pct,overall}}
function trainingStats(state){const sessions=state.analytics?.sessions||[],attempts=sessions.reduce((t,s)=>t+(Array.isArray(s.results)?s.results.length:0),0),correct=sessions.reduce((t,s)=>t+(Array.isArray(s.results)?s.results.filter(r=>r.correct).length:0),0);return{reps:sessions.length,accuracy:attempts?Math.round(correct/attempts*100):null,xp:state.game.xp||0,level:state.game.level||1,bestCombo:state.game.bestCombo||0,timeMinutes:Math.floor((state.game.trainingSeconds||0)/60)}}
function footballIQScore(state){const stats=trainingStats(state);if(!stats.reps&&!Number.isFinite(stats.accuracy))return null;return Math.min(99,Math.round((stats.accuracy||50)*.65+Math.min(30,stats.bestCombo*3)+5));}
function renderIdentityModule(state,metrics){const iq=footballIQScore(state);return `<section class="home-hero-card home-hero-locked"><div class="home-hero-grid"><div class="home-hero-left"><div class="home-streak">🔥 ${state.game.streak} day streak • ${metrics.rank}</div><div class="home-greeting"><span>Good afternoon,</span><b>${escapeHtml(state.profile.name||"Player")}</b></div></div><div class="home-hero-center"><div class="home-player-figure"><img class="home-player-avatar" src="assets/players/player-avatar.png" alt="Academy player"></div></div><div class="home-hero-right"><div class="home-ovr-panel"><small>OVR</small><b>${metrics.overall}</b><small>Position</small><strong>${escapeHtml(positionLabel(state.profile.position))}</strong><small>Style</small><strong>${escapeHtml(state.profile.style||"Creator")}</strong></div></div></div></section>`}
export function renderHome(state){const metrics=homeMetrics(state);return `<section class="screen app home-aaa home-v7 active" id="home"><section class="home-v7-grid">${renderIdentityModule(state,metrics)}</section></section>`}
export function renderResults(){return `<section class="screen app results-v2 active" id="results"><div class="results-v2-wrap"><header class="results-v2-hero"><span class="kicker">Results</span><h1>NO RESULTS YET</h1></header></div></section>`}
export function renderTraining(){return `<section class="screen app training-reactive active" id="training"><main class="reactive-core"><div class="reactive-cue">SCAN</div></main></section>`}
export function renderCamera(){return `<section class="screen app camera-full active" id="camera"></section>`}
export function renderReward(){return `<section class="screen center reward active" id="reward"></section>`}

function playerEditorMarkup(state){const profile=state.profile||{},field=escapeHtml(profile.name||"Player");return `<aside class="player-editor-panel" id="playerEditorPanel" hidden aria-label="Edit player"><form class="player-editor-card" data-player-editor-form><header><div><span class="kicker">Edit player</span><h2 id="playerEditorTitle">Player detail</h2></div><button type="button" data-action="player-editor-close" aria-label="Close editor">×</button></header><div id="playerEditorBody"></div><div class="player-editor-actions"><button type="button" data-action="player-editor-close">Cancel</button><button class="primary" type="submit">Save changes</button></div></form></aside>`}
export function renderPlayer(state){const rank=rankForLevel(state.game.level),need=xpNeed(state.game.level),pct=Math.min(100,Math.round(state.game.xp/need*100)),iq=footballIQScore(state),number=state.profile.number??1,style=state.profile.style||"Creator";return `<section class="screen app player-v3 player-v4 active" id="player"><div class="player-v3-wrap"><header class="player-v3-header player-v4-header"><div><span class="kicker">Player profile</span><h1>${escapeHtml(state.profile.name||"PLAYER")}</h1><p>${escapeHtml(positionLabel(state.profile.position))} • ${escapeHtml(rank)}</p></div></header><article class="player-v3-identity"><div class="player-v3-avatar"><img src="assets/players/player-avatar.png" alt="${escapeHtml(state.profile.name||"Player")} avatar"></div><div class="player-v3-overall"><small>Overall</small><b>${playerOverall(state)}</b></div><div class="player-v3-iq"><small>Football IQ</small><b>${iq??"--"}</b></div><div class="player-v3-progress"><span>PitchIQ Level ${state.game.level}</span><div class="xpbar"><i style="width:${pct}%"></i></div><small>${state.game.xp} / ${need} XP</small></div></article><section class="player-v4-details"><header><span>Player identity</span><small>Your football profile</small></header><div class="player-v4-detail-grid"><article><small>Name</small><b>${escapeHtml(state.profile.name||"Player")}</b></article><article><small>Number</small><b>${escapeHtml(number)}</b></article><article><small>Position</small><b>${escapeHtml(positionLabel(state.profile.position))}</b></article><article><small>Player style</small><b>${escapeHtml(style)}</b></article></div></section><section class="player-v3-management player-v4-management"><span>Manage player</span><p>Edit identity and account options without leaving the Player tab.</p><button data-action="player-settings-open">Open player options</button></section><aside class="player-settings-panel" id="playerSettingsPanel" hidden><div class="player-settings-card"><header><div><span class="kicker">Manage player</span><h2>${escapeHtml(state.profile.name||"Player")}</h2></div><button data-action="player-settings-close" aria-label="Close player options">×</button></header><div class="player-settings-actions"><button data-player-option="name">Edit name</button><button data-player-option="number">Edit number</button><button data-player-option="position">Edit position</button><button data-player-option="style">Edit player style</button><button data-player-option="avatar">Change avatar</button><button data-player-option="feedback">Send feedback</button><button class="player-reset-button" data-action="reset">Reset Player</button></div></div></aside>${playerEditorMarkup(state)}</div></section>`}
export function renderPlayerEditor(field,state){const profile=state.profile||{};if(field==="name")return {title:"Edit name",body:`<label>Player name<input name="value" maxlength="18" required value="${escapeHtml(profile.name||"")}"></label>`};if(field==="number")return {title:"Edit number",body:`<label>Jersey number<input name="value" type="number" min="0" max="99" required value="${escapeHtml(profile.number??1)}"></label>`};if(field==="position")return {title:"Edit position",body:`<label>Preferred position<select name="value">${PLAYER_POSITIONS.map(([code,label])=>`<option value="${code}" ${profile.position===code?"selected":""}>${escapeHtml(label)}</option>`).join("")}</select></label>`};if(field==="style")return {title:"Edit player style",body:`<label>Player style<select name="value">${PLAYER_STYLES.map(style=>`<option value="${escapeHtml(style)}" ${profile.style===style?"selected":""}>${escapeHtml(style)}</option>`).join("")}</select></label>`};if(field==="avatar")return {title:"Change avatar",body:`<p class="player-editor-note">One avatar is currently available. Additional avatars will be added later.</p><input type="hidden" name="value" value="default"><div class="player-avatar-choice selected"><img src="assets/players/player-avatar.png" alt="Current avatar"><span>Current avatar</span></div>`};if(field==="feedback")return {title:"Send feedback",body:`<label>Feedback<textarea name="value" rows="5" maxlength="600" required placeholder="Tell us what would make PitchIQ better."></textarea></label>`};return null;}
export function renderNav(){return routeNames.map(route=>`<button data-route="${route}"><span>${route==="training"?"Train":route[0].toUpperCase()+route.slice(1)}</span></button>`).join("")}
